name: esv_api
description: A Dart client for the ESV API from Crossway. Can be used to
  download scripture from the ESV Bible.
version: 0.1.2
homepage: https://github.com/tsteward/esv_api_dart
author: Timothy Steward <tsteward0@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0
  http: ^0.12.0+1
  meta: ^1.1.7

dev_dependencies:
  build_runner: ^1.2.8
  json_serializable: ^2.0.2
  pedantic: ^1.0.0
  test: ^1.0.0
